#!/usr/bin/env python3
"""Generate WCS-BIM test case catalog (CSV + Markdown). Stdlib only."""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

# Area, Case, Input, Expected, Suite, WCS_BIM_Test, Status
ROWS = [
    [
        "Auth",
        "Valid login",
        "Known user credentials",
        "Session created, home opens",
        "UI/Integration",
        "—",
        "n/a",
    ],
    [
        "Auth",
        "Invalid login",
        "Bad password",
        "Error shown, no session",
        "Unit/UI",
        "—",
        "n/a",
    ],
    [
        "Auth",
        "Session restore",
        "Existing token",
        "User returns to last state",
        "Integration",
        "—",
        "n/a",
    ],
    [
        "Onboarding",
        "First launch",
        "Fresh install",
        "Intro flow appears once",
        "UI",
        "WCS_BIMUITestsLaunchTests.testLaunch",
        "partial",
    ],
    [
        "Onboarding",
        "Skip onboarding",
        "Skip action",
        "Home loads immediately",
        "UI",
        "Tier1SmokeUITests.testAppShellTabsVisible",
        "implemented",
    ],
    [
        "Core",
        "Primary action success",
        "Valid payload",
        "Action completes and persists",
        "Integration/UI",
        "Tier1SmokeUITests.testCreateProjectCoreAction",
        "implemented",
    ],
    [
        "Core",
        "Primary action failure",
        "Server error",
        "Graceful error and retry path",
        "Unit/Integration",
        "OpenAIResponseContractTests",
        "partial",
    ],
    [
        "Sync",
        "Offline save",
        "No network",
        "Local queue stores data",
        "Unit/Integration",
        "ModelContainerBootstrapTests",
        "implemented",
    ],
    [
        "Sync",
        "Reconnect sync",
        "Network restored",
        "Queued data syncs",
        "Integration",
        "SwiftData disk store (ArchFusion_v11)",
        "partial",
    ],
    [
        "Settings",
        "Change preference",
        "Toggle setting",
        "Setting persists after relaunch",
        "Unit/Integration/UI",
        "AppSettingsUpdaterTests + Tier3ScreenUITests.testSettingsScreen",
        "implemented",
    ],
    [
        "Notifications",
        "Permission grant",
        "Allow notifications",
        "Token registered",
        "Manual/UI",
        "—",
        "planned",
    ],
    [
        "Notifications",
        "Permission deny",
        "Deny notifications",
        "Fallback path works",
        "Manual/UI",
        "—",
        "planned",
    ],
    [
        "Performance",
        "Cold launch",
        "App starts from terminated state",
        "Launch within target",
        "Perf",
        "Tier5PerformanceUITests.testLaunchPerformance",
        "implemented",
    ],
    [
        "Performance",
        "Scroll smoothness",
        "Long feed",
        "No visible jank",
        "Perf/UI",
        "AllUIUnitsUITests.testAllUIUnitsEndToEnd",
        "implemented",
    ],
]

COLUMNS = [
    "Area",
    "Case",
    "Input",
    "Expected",
    "Suite",
    "WCS_BIM_Test",
    "Status",
]

TIER_MAP = """
| Catalog suite | WCS-BIM target |
|---------------|----------------|
| Unit | WCS-BIMTests (fast: test-fast.sh) |
| UI | WCS-BIMUITests Tier1–3 |
| Integration | ModelContainerBootstrapTests, AppSettingsUpdaterTests |
| Perf | Tier5PerformanceUITests |
| Manual | Not automated |
"""


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out = root / "output"
    out.mkdir(exist_ok=True)

    csv_path = out / "wcs_bim_test_case_catalog.csv"
    with csv_path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(COLUMNS)
        writer.writerows(ROWS)

    by_area: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in ROWS:
        by_area[row[0]].append(dict(zip(COLUMNS, row)))

    md: list[str] = [
        "# WCS-BIM Test Case Catalog",
        "",
        "Generated by `scripts/generate-test-catalog.py`.",
        "",
        "## Tier mapping",
        TIER_MAP.strip(),
        "",
    ]

    seen_areas: list[str] = []
    for row in ROWS:
        if row[0] not in seen_areas:
            seen_areas.append(row[0])

    for area in seen_areas:
        md.append(f"## {area}")
        md.append("")
        for r in by_area[area]:
            md.append(
                f"- **{r['Case']}** ({r['Status']}) — "
                f"Input: {r['Input']}; Expected: {r['Expected']}; "
                f"Suite: {r['Suite']}; Test: `{r['WCS_BIM_Test']}`."
            )
        md.append("")

    md_path = out / "wcs_bim_test_case_catalog.md"
    md_path.write_text("\n".join(md))

    print(csv_path)
    print(md_path)
    for row in ROWS[:3]:
        print("\t".join(row[:5]))


if __name__ == "__main__":
    main()
