name: Container Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/wcs-bim-api:${{ github.sha }}
      - uses: docker/build-push-action@v6
        with:
          context: ./ml-service
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/wcs-bim-ml:${{ github.sha }}
